services:
  - type: web
    name: weather-app
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false

